platform :ios, '14.1'
source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  use_frameworks!
  pod 'shared', :path => '../app-shared'
  pod 'OpenKuiklyIOSRender', :git => 'https://github.com/Tencent-TDS/KuiklyUI.git', :tag => '2.16.0'
  pod 'SDWebImage'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
    end
  end
end
