package com.example.kuikly.navigation

object PageNames {
    const val HelloWorld = "HelloWorld"
    const val Splash = "Splash"
    const val Main = "Main"
    const val Home = "Home"
    const val Login = "Login"
    const val UsedCarList = "UsedCarList"
    const val UsedCarDetail = "UsedCarDetail"
    const val FeedList = "FeedList"
    const val FeedDetail = "FeedDetail"
    const val DslLab = "DslLab"
    const val PerfLab = "PerfLab"
    const val Gallery = "Gallery"
    const val ComposeAnim = "ComposeAnim"
    const val ComposeList = "ComposeList"
    const val ComposePager = "ComposePager"
    const val PermissionDemo = "PermissionDemo"
    const val ShareDemo = "ShareDemo"
    const val Settings = "Settings"
    const val Search = "Search"
    const val ChatDetail = "ChatDetail"
    const val PostDetail = "PostDetail"
    const val VideoList = "VideoList"
    const val VideoDetail = "VideoDetail"
    const val MusicList = "MusicList"
    const val MusicNowPlaying = "MusicNowPlaying"
    const val CommunityPublish = "CommunityPublish"
    const val AllServices = "AllServices"
    const val HotRankDetail = "HotRankDetail"
    const val Strategy = "Strategy"
    const val LearningReport = "LearningReport"
    const val CheckInMall = "CheckInMall"
    const val ClassroomList = "ClassroomList"
    const val ClassroomDetail = "ClassroomDetail"
    const val FriendList = "FriendList"
    const val FriendDetail = "FriendDetail"
    const val LiveList = "LiveList"
    const val LiveDetail = "LiveDetail"
    const val PayList = "PayList"
    const val PayConfirm = "PayConfirm"
}
